### Send POST request with json body
POST localhost:8080/api/user/
Content-Type: application/json

{
  "firstname": "Simon",
  "lastname": "Brebeck",
  "email": "simonbrebeck@yahoo.de"
}
> {%
    client.global.set("auth_token", response.body["token"]);
%}

### Create Bucket
POST localhost:8080/api/buckets/?bucket=TestBucket
Authorization: Bearer {{auth_token}}

### Create Directory in bucket
POST localhost:8080/api/buckets/directory/?bucket=TestBucket&directory=MeinSpeicher
Authorization: Bearer {{auth_token}}

### Create Directory in directory in bucket
POST localhost:8080/api/buckets/directory/?bucket=TestBucket&parentDirectory=MeinSpeicher&directory=MehrSpeicher
Authorization: Bearer {{auth_token}}

### Upload file to bucket
POST localhost:8080/api/buckets/files/?bucket=TestBucket&dir=MeinSpeicher
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testfile.txt"

// File content
< ./testfile.txt

### Download file from bucket and directory
GET localhost:8080/api/buckets/download/TestBucket/MeinSpeicher/testfile.txt
Authorization: Bearer {{auth_token}}